language: csharp
sudo: true
dist: trusty
mono: none
dotnet: 2.1

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  # Install Kudu from the Cloudera apt repository.
  - curl https://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key | sudo apt-key add -
  - sudo wget http://archive.cloudera.com/kudu/ubuntu/trusty/amd64/kudu/cloudera.list -O /etc/apt/sources.list.d/cloudera.list
  - sudo apt-get update -y -qq
  - sudo apt-get install -y kudu kudu-master kudu-tserver

script:
  - dotnet build --configuration Release
  - dotnet test --no-restore --no-build --configuration Release test/Kudu.Client.Tests
  - dotnet test --no-restore --no-build --configuration Release test/Kudu.Client.FunctionalTests
