language: csharp
sudo: true
dist: trusty
mono: none
dotnet: 2.1

install:
  # Install Kudu from the Cloudera apt repository.
  - curl http://archive.cloudera.com/kudu/ubuntu/trusty/amd64/kudu/archive.key | sudo apt-key add -
  - sudo wget http://archive.cloudera.com/kudu/ubuntu/trusty/amd64/kudu/cloudera.list -O /etc/apt/sources.list.d/cloudera.list
  - sudo apt-get update -y -qq
  - sudo apt-get install -y kudu kudu-master kudu-tserver

script:
  - dotnet build --configuration Release
  - dotnet test --no-restore --no-build --configuration Release test\Kudu.Client.Tests
