language: csharp
os: linux
dist: bionic
mono: none
dotnet: 3.1

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - SASL_PATH: $TRAVIS_BUILD_DIR/kudu-binary/lib/sasl2

install:
  - echo $SASL_PATH

script:
  #- dotnet build --configuration Release
  #- dotnet test --no-restore --no-build --configuration Release
