language: csharp
os: linux
dist: bionic
mono: none
dotnet: 3.1

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - KUDU_BIN_PATH: $TRAVIS_BUILD_DIR/kudu-binary/bin
    - SASL_PATH: $TRAVIS_BUILD_DIR/kudu-binary/lib/sasl2

install:
  # Install Kudu binary for integration tests
  # https://kudu.apache.org/2019/03/19/testing-apache-kudu-applications-on-the-jvm.html
  - wget --output-document=kudu-binary.jar https://repository.apache.org/content/repositories/orgapachekudu-1061/org/apache/kudu/kudu-binary/1.12.0/kudu-binary-1.12.0-linux-x86_64.jar
  - unzip kudu-binary.jar
  - mv kudu-binary-1.12.0-linux-x86_64 kudu-binary
  - chmod +x kudu-binary/bin/kudu
  - chmod +x kudu-binary/bin/kudu-master
  - chmod +x kudu-binary/bin/kudu-tserver

script:
  - dotnet build --configuration Release
  - dotnet test --no-restore --no-build --configuration Release
